version: "3"

services:

  runtime-setup:
    image: swift-nio:16.04-5.2
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.2-xenial"

  unit-tests:
    image: swift-nio:16.04-5.2

  integration-tests:
    image: swift-nio:16.04-5.2
    environment:
      - INTEGRATION_TESTS_ARG=-f tests_0[013-9]

  test:
    image: swift-nio:16.04-5.2
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=30600
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=592100
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4600
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99100
      - MAX_ALLOCS_ALLOWED_creating_10000_headers=10100
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150
      - MAX_ALLOCS_ALLOWED_modifying_1000_circular_buffer_elements=50
      - SANITIZER_ARG=--sanitize=thread
      - INTEGRATION_TESTS_ARG=-f tests_0[013-9]

  performance-test:
    image: swift-nio:16.04-5.2

  shell:
    image: swift-nio:16.04-5.2

  echo:
    image: swift-nio:16.04-5.2

  http:
    image: swift-nio:16.04-5.2
