name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  macos:
    name: macOS ${{ matrix.configuration }}
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        xcode: [latest, latest-stable]
        configuration: [debug, release, release_testing]
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version:  ${{ matrix.xcode }}
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Release Build
      if: matrix.configuration == 'release'
      run: swift build -c release
    - name: Release Build & Test
      if: matrix.configuration == 'release_testing'
      run: swift test -c release -Xswiftc -enable-testing
    - name: Debug Build & Test
      if: matrix.configuration == 'debug'
      run: swift test -c debug